### PR TITLE
[bugfix] Fix #112 App is crashing on iOS if token provided is null

### LINKED ISSUE #112: [bug] App is crashing in iOS when passing a null token to sendTokenToIntercom method channel
### Description

This can be handled in Flutter, eg. flagging calls to `sendTokenToIntercom` when token is `null`, but let's assume some devs might missed it - it will be a difficult thing to trace.

### Steps to Replicate

1. Using the example app, add method call and send token as `null`
```
class SampleApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    Intercom.sendTokenToIntercom(null); // Add this
    return MaterialApp(
       ....
    );
  }
}
```

2. Run the app

### Expected State

App should not crash. It should swallow the error just like the other method calls in the class.

### Actual State

App is crashing without sending any warning/log to Flutter

It ends here

```
Performing hot restart...                                               
Restarted application in 541ms.
flutter: Start sending token to Intercom
Lost connection to device.
```

### PR DESCRIPTION
**Pull request by joshuadeguzman**
## Description

When `token` provided is null, app crashes in iOS.

## Tickets

- Closes #112

### Steps to Replicate

1. Using the example app, add method call and send token as `null`
```
class SampleApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    Intercom.sendTokenToIntercom(null); // Add this
    return MaterialApp(
       ....
    );
  }
}
```

2. Run the app

### Expected State

App should not crash. It should swallow the error just like the other method calls in the class.

### CODE REVIEW

**Comment by joshuadeguzman** [comment]
If it make sense, we can also flag it within the Dart plugin. Since the canonical way to remove user session is through `logout` anyway, instead of sending a `null` token.

```
static Future<dynamic> sendTokenToIntercom(String token) {
    print("Start sending token to Intercom"); // Ideally, this should be changed.
    return _channel.invokeMethod('sendTokenToIntercom', {'token': token});
  }
```

cc: @v3rm0n

**Review by Zazo032 — APPROVED** [review]
Hi @joshuadeguzman, thanks for the PR.

I see Android has this behavior: https://github.com/v3rm0n/intercom_flutter/blob/master/android/src/main/kotlin/io/maido/intercom/IntercomFlutterPlugin.kt#L139

This could later be avoided when migrated to nullsafety, or we could also assert there if token is null or empty.

Changes LGTM

**Comment by joshuadeguzman** [comment]
> This could later be avoided when migrated to nullsafety, or we could also assert there if token is null or empty.

Sure, just added a flag for the log to avoid confusion.

Thanks @Zazo032!

File: lib/intercom_flutter.dart [hunk 1]
```diff
@@ -121,7 +121,9 @@ class Intercom {
   }
 
   static Future<dynamic> sendTokenToIntercom(String token) {
-    print("Start sending token to Intercom");
+    if (token != null && token.isNotEmpty) {
+      print("Start sending token to Intercom");
+    }
```
Comment (Zazo032) [inline lib/intercom_flutter.dart]: This might be a cleaner solution:
```suggestion
    assert(token != null && token.isNotEmpty);
    print("Start sending token to Intercom");
```
What do you think? In native code, null tokens are ignored with this PR, so maybe an assertion will notice developers while debugging it. Assertions are stripped from release builds.

Comment (joshuadeguzman) [reply lib/intercom_flutter.dart]: Thanks @Zazo032!
