### PR TITLE
[7.6.1] Added extra docs for Android notifications and updated dependencies

### LINKED ISSUE #270: [7.6.0]: Android: Exception After Background Push Received
When a new user registers and tries to access the intercom it's registered the first time and displays the chat window perfectly. But, When the user starts sending messages it's worked after that user closes the application. And the user gets notified by the intercom user and a push notification got on clicked push notification application getting crashed. After this crash user never opens messanger screen. The user got this crashed every time.

**My Code**

```
Future<void> loginIntercom() async {
    String? isUserLoggedIn = await _localStorage.readSecureData(LocalStorage.keyIsIntercomUserLoggedIn);
    if (isUserLoggedIn == "true") {
      await Intercom.instance.displayMessenger();
    } else {
      try {
        WidgetsBinding.instance.addPostFrameCallback((timeStamp) async {
          await _showLoadingDialog();
        });
        final key = utf8.encode(Platform.isAndroid
            ? IntercomConst.instance.androidSecretKey
            : Platform.isIOS
                ? IntercomConst.instance.iOsSecretKey
                : "");
        final bytes = utf8.encode(loggedInUserInfo.value.mail ?? "");

        final hmacSha256 = Hmac(sha256, key);
        final digest = hmacSha256.convert(bytes);
        print("User Hash ==> ${digest.toString()}");
        await Intercom.instance.setUserHash(digest.toString());

        Intercom.instance.loginIdentifiedUser(
            email: loggedInUserInfo.value.mail ?? "",
            statusCallback: IntercomStatusCallback(
              onSuccess: () async {
                await _localStorage.writeSecureData(LocalStorage.keyIsIntercomUserLoggedIn, "true");
                await Intercom.instance.updateUser(userId: loggedInUserInfo.value.id ?? "", name: loggedInUserInfo.value.displayName ?? "");
                Get.back();
                await Intercom.instance.displayMessenger();
              },
              onFailure: (error) {
                Get.back();
                Intercom.instance.logout();
                if (kDebugMode) {
                  print("Intercom Exception ==> $error");
                }
              },
            ));
      } catch (ex) {
        if (kDebugMode) {
          print("Intercom Exception ==> $ex");
        }
        Intercom.instance.logout();
        Get.back();
      }
    }
  }
```

Exception
```

D/ConnectivityManager(17921): StackLog: [android.net.ConnectivityManager.sendRequestForNetwork(ConnectivityManager.java:4186)] [android.net.ConnectivityManager.sendRequestForNetwork(ConnectivityManager.java:4228)] [android.net.ConnectivityManager.registerNetworkCallback(ConnectivityManager.java:4610)] [android.net.ConnectivityManager.registerNetworkCallback(ConnectivityManager.java:4580)] [coil.network.RealNetworkObserver.<init>(NetworkObserver.kt:88)] [coil.network.NetworkObserverKt.NetworkObserver(NetworkObserver.kt:33)] [coil.util.SystemCallbacks.<init>(SystemCallbacks.kt:31)] [coil.RealImageLoader.<init>(RealImageLoader.kt:78)] [coil.ImageLoader$Builder.build(ImageLoader.kt:517)] [io.intercom.android.sdk.utilities.IntercomCoilKt.getImageLoader(IntercomCoil.kt:51)] [io.intercom.android.sdk.utilities.IntercomCoilKt.loadIntercomImage(IntercomCoil.kt:19)] [io.intercom.android.sdk.utilities.AvatarUtils.createAvatar(AvatarUtils.java:69)] [io.intercom.android.sdk.utilities.AvatarUtils.loadAvatarIntoView(AvatarUtils.java:58)] [io.intercom.android.sdk.overlay.StackableSnippet.setViewData(StackableSnippet.java:92)] [io.intercom.android.sdk.overlay.StackableSnippet.display(StackableSnippet.java:49)] [io.intercom.android.sdk.overlay.InAppNotificationPresenter.addNewNotifications(InAppNotificationPresenter.java:184)] [io.intercom.android.sdk.overlay.InAppNotificationPresenter.displayNotificationsAfterAttach(InAppNotificationPresenter.java:90)] [io.intercom.android.sdk.overlay.InAppNotificationPresenter$1.run(InAppNotificationPresenter.java:79)] [io.intercom.android.sdk.utilities.ViewUtils$1.onGlobalLayout(ViewUtils.java:30)] [android.view.ViewTreeObserver.dispatchOnGlobalLayout(ViewTreeObserver.java:1080)] [android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:4098)] [android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:2924)] [android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:10513)] [android.view.Choreographer$CallbackRecord.run(Choreographer.java:1108)] [android.view.Choreographer.doCallbacks(Choreographer.java:866)] [android.view.Choreographer.doFrame(Choreographer.java:797)] [android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1092)]
D/AndroidRuntime(17921): Shutting down VM
E/AndroidRuntime(17921): FATAL EXCEPTION: main
E/AndroidRuntime(17921): Process: com.alliancetek.dvrc, PID: 17921
E/AndroidRuntime(17921): java.lang.IllegalStateException: ViewTreeLifecycleOwner not found from android.widget.FrameLayout{3a06f66 V.E...... ......ID 0,0-1080,2274 #7f080190 app:id/intercom_overlay_root}
E/AndroidRuntime(17921): 	at androidx.compose.ui.platform.WindowRecomposer_androidKt.createLifecycleAwareWindowRecomposer(WindowRecomposer.android.kt:349)
E/AndroidRuntime(17921): 	at androidx.compose.ui.platform.WindowRecomposer_androidKt.createLifecycleAwareWindowRecomposer$default(WindowRecomposer.android.kt:324)
E/AndroidRuntime(17921): 	at androidx.compose.ui.platform.WindowRecomposerFactory$Companion$LifecycleAware$1.createRecomposer(WindowRecomposer.android.kt:168)
E/AndroidRuntime(17921): 	at androidx.compose.ui.platform.WindowRecomposerPolicy.createAndInstallWindowRecomposer$ui_release(WindowRecomposer.android.kt:224)
E/AndroidRuntime(17921): 	at androidx.compose.ui.platform.WindowRecomposer_androidKt.getWindowRecomposer(WindowRecomposer.android.kt:299)
E/AndroidRuntime(17921): 	at androidx.compose.ui.platform.AbstractComposeView.resolveParentCompositionContext(ComposeView.android.kt:242)
E/AndroidRuntime(17921): 	at androidx.compose.ui.platform.AbstractComposeView.ensureCompositionCreated(ComposeView.android.kt:249)
E/AndroidRuntime(17921): 	at androidx.compose.ui.platform.AbstractComposeView.createComposition(ComposeView.android.kt:194)
E/AndroidRuntime(17921): 	at androidx.compose.ui.platform.ComposeView.setContent(ComposeView.android.kt:420)
E/AndroidRuntime(17921): 	at io.intercom.android.sdk.m5.notification.InAppNotificationCardKt.addTicketHeaderToCompose(InAppNotificationCard.kt:55)
E/AndroidRuntime(17921): 	at io.intercom.android.sdk.overlay.StackableSnippet.setViewData(StackableSnippet.java:101)
E/AndroidRuntime(17921): 	at io.intercom.android.sdk.overlay.StackableSnippet.display(StackableSnippet.java:49)
E/AndroidRuntime(17921): 	at io.intercom.android.sdk.overlay.InAppNotificationPresenter.addNewNotifications(InAppNotificationPresenter.java:184)
E/AndroidRuntime(17921): 	at io.intercom.android.sdk.overlay.InAppNotificationPresenter.displayNotificationsAfterAttach(InAppNotificationPresenter.java:90)
E/AndroidRuntime(17921): 	at io.intercom.android.sdk.overlay.InAppNotificationPresenter$1.run(InAppNotificationPresenter.java:79)
E/AndroidRuntime(17921): 	at io.intercom.android.sdk.utilities.ViewUtils$1.onGlobalLayout(ViewUtils.java:30)
E/AndroidRuntime(17921): 	at android.view.ViewTreeObserver.dispatchOnGlobalLayout(ViewTreeObserver.java:1080)
E/AndroidRuntime(17921): 	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:4098)
E/AndroidRuntime(17921): 	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:2924)
E/AndroidRuntime(17921): 	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:10513)
E/AndroidRuntime(17921): 	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1108)
E/AndroidRuntime(17921): 	at android.view.Choreographer.doCallbacks(Choreographer.java:866)
E/AndroidRuntime(17921): 	at android.view.Choreographer.doFrame(Choreographer.java:797)
E/AndroidRuntime(17921): 	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1092)
E/AndroidRuntime(17921): 	at android.os.Handler.handleCallback(Handler.java:938)
E/AndroidRuntime(17921): 	at android.os.Handler.dispatchMessage(Handler.java:99)
E/AndroidRuntime(17921): 	at android.os.Looper.loopOnce(Looper.java:226)
E/AndroidRuntime(17921): 	at android.os.Looper.loop(Looper.java:313)
E/AndroidRuntime(17921): 	at android.app.ActivityThread.main(ActivityThread.java:8751)
E/AndroidRuntime(17921): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(17921): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
E/AndroidRuntime(17921): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1135)
I/Process (17921): Sending signal. PID: 17921 SIG: 9
Lost connection to device.
```

### PR DESCRIPTION
**Pull request by Zazo032**
Fixes #270 

## 7.6.1

* Bump Intercom iOS SDK version to 14.0.2
* Bump Intercom Android SDK version to 14.0.3
* Added extra documentation to fix Android exception after background push notification is received ([#270](https://github.com/v3rm0n/intercom_flutter/issues/270#issuecomment-1330510979))

### CODE REVIEW

File: intercom_flutter/example/android/app/src/main/kotlin/io/maido/intercomexample/MainActivity.kt [hunk 1]
```diff
@@ -1,6 +0,0 @@
-package io.maido.intercomexample
-
-import io.flutter.embedding.android.FlutterActivity
-
-class MainActivity() : FlutterActivity() {
-}
```
Comment (deepak786) [inline intercom_flutter/example/android/app/src/main/kotlin/io/maido/intercomexample/MainActivity.kt:6]: We should keep this file and extend it with `FlutterFragmentActivity`

Comment (Zazo032) [reply intercom_flutter/example/android/app/src/main/kotlin/io/maido/intercomexample/MainActivity.kt:6]: Why? It's not being used, so I imported it directly in the manifest

Comment (deepak786) [reply intercom_flutter/example/android/app/src/main/kotlin/io/maido/intercomexample/MainActivity.kt:6]: This will be easy to understand for the users. And thats what is mentioned in docs.

**Review by deepak786 — APPROVED** [review]
LGTM
