### PR TITLE
Fix 'registerIdentifiedUser arguments conflict'

### LINKED ISSUE #10: registerIdentifiedUser arguments conflict
I would like to suggest to only allow either userId or email for registerIdentifiedUser. Allowing both complicates usage and may result in undocumente behaviour as given userId and email might match different users. I had to look into kt code to see that giving email overrides the userId.

### PR DESCRIPTION
**Pull request by Zazo032**
Also, added some trailing commas and indentation.

Fixes #10

### CODE REVIEW

**Comment by Zazo032** [comment]
Tried to add `registerIdentifiedUser` tests for `with userId and email` and `without userId or email` but can't make them pass. Maybe some changes are needed in `intercom_flutter.dart` to handle better the assertions and end up with a passing test.

File: lib/intercom_flutter.dart [hunk 1]
```diff
@@ -27,22 +27,22 @@ class Intercom {
...
           'The parameter `userId` must be null if `email` is provided.');
       return _channel.invokeMethod('registerIdentifiedUser', {
         'email': email,
       });
     } else {
-      assert(userId.isNotEmpty || email.isNotEmpty,
+      assert(userId == null || email == null,
           'An identification method must be provided as a parameter, either `userId` or `email`.');
-      return registerUnidentifiedUser();
+      return _channel.invokeMapMethod('registerUnidentifiedUser');
```
Comment (Zazo032) [inline lib/intercom_flutter.dart]: If no `userId` or `email` is provided, I added a call to `registerUnidentifiedUser`. In debug mode it will throw the `assert` but maybe in release mode, if no arguments are provided, I think we should register an Unidentified user (I don't know how Intercom handles this case).

File: lib/intercom_flutter.dart [hunk 2]
```diff
@@ -27,22 +27,22 @@ class Intercom {
   }
 
   static Future<dynamic> registerIdentifiedUser({String userId, String email}) {
-    if (userId.isNotEmpty) {
```
Comment (Zazo032) [inline lib/intercom_flutter.dart]: Maybe we should also check if the `String` is empty.

File: lib/intercom_flutter.dart (hunk 1 above)
Comment (GeertJohan) [reply lib/intercom_flutter.dart]: If the developer asks to do X in a wrong way, the package shouldnt do Y. Instead, throw an exception that X was called with invalid arguments.

So, I wouldnt call registerUnidientifiedUser when there is no argument given to registerIdentifiedUser. Instead return an exception.

Comment (Spikes042) [reply lib/intercom_flutter.dart]: This makes sense. Might be a case of a null/empty variable passed in

File: lib/intercom_flutter.dart (hunk 2 above)
Comment (Zazo032) [reply lib/intercom_flutter.dart]: Solved using `userId?.isNotEmpty ?? false`, which checks if `userId` is not empty only if it's not null, otherwise the logical expression is evaluated to false.

File: lib/intercom_flutter.dart (hunk 1 above)
Comment (Zazo032) [reply lib/intercom_flutter.dart]: Solved, now it returns an `ArgumentError` if no or both parameters are passed in.

**Comment by v3rm0n** [comment]
👍

**Comment by v3rm0n** [comment]
Released as `2.0.1`
